import { NextRequest, NextResponse } from "next/server"
import { PDFDocument, StandardFonts, rgb, PDFPage, PDFFont } from "pdf-lib"
import { supabaseAdmin } from "@/lib/supabase-server"
import { verifyToken } from "@/lib/auth/jwt"

const EUDR_SCRIPT_VERSION = "2.3.1"
const PAGE_W = 595
const PAGE_H = 842
const ML = 40          // margin left
const MR = PAGE_W - 40 // margin right
const MB = 55          // margin bottom
const TEAL = rgb(0.165, 0.757, 0.639)   // #2ac1a3
const DARK = rgb(0.1,   0.1,   0.1)
const GRAY = rgb(0.45,  0.45,  0.45)
const LIGHT = rgb(0.96, 0.96, 0.96)
const WHITE = rgb(1, 1, 1)

type Lang = "fr" | "en"

interface Dict {
  dateLocale: string
  orgName: string
  ddsLabel: string
  subtitle: string
  emittedOn: string
  filenamePrefix: string
  // Section 1
  section1: string
  fieldLot: string
  fieldProduct: string
  fieldWeight: string
  fieldOrigin: string
  fieldDest: string
  fieldBuyer: string
  // Section 2
  section2: string
  colParcel: string
  colSurface: string
  colType: string
  colLat: string
  colLon: string
  colGeojson: string
  typePoint: string
  typePolygon: string
  geojsonOui: string
  geojsonNon: string
  // Footer
  footerLeft: (adminName: string, adminCode: string, date: string) => string
  footerRight: string
  // Errors
  errNotAuthed: string
  errInvalidToken: string
  errAdminOnly: string
  errLotNotFound: string
  errInternal: string
}

const DICTS: Record<Lang, Dict> = {
  fr: {
    dateLocale: "fr-FR",
    orgName: "ID BASSIN CONGO",
    ddsLabel: "DUE DILIGENCE STATEMENT",
    subtitle: "Pays de production et géolocalisation des parcelles",
    emittedOn: "Émis le",
    filenamePrefix: "DDS",
    section1: "1. INFORMATIONS SUR LE LOT",
    fieldLot: "N° LOT",
    fieldProduct: "PRODUIT",
    fieldWeight: "POIDS TOTAL",
    fieldOrigin: "PAYS D'ORIGINE",
    fieldDest: "DESTINATION",
    fieldBuyer: "ACHETEUR",
    section2: "2. PARCELLES ET GÉOLOCALISATION",
    colParcel: "ID PARCELLE",
    colSurface: "SURFACE (HA)",
    colType: "TYPE",
    colLat: "LAT.",
    colLon: "LONG.",
    colGeojson: "GEOJSON",
    typePoint: "Point",
    typePolygon: "Polygone",
    geojsonOui: "Oui",
    geojsonNon: "—",
    footerLeft: (name, code, date) =>
      `GÉNÉRÉ PAR ID BASSIN CONGO · SCRIPT EUDR V${EUDR_SCRIPT_VERSION}\nADMIN : ${name} (${code}) · ${date}`,
    footerRight: "DOCUMENT GÉNÉRÉ AUTOMATIQUEMENT — ID BASSIN CONGO",
    errNotAuthed: "Non authentifié",
    errInvalidToken: "Token invalide",
    errAdminOnly: "Réservé aux administrateurs",
    errLotNotFound: "Lot non trouvé",
    errInternal: "Erreur interne",
  },
  en: {
    dateLocale: "en-GB",
    orgName: "ID BASSIN CONGO",
    ddsLabel: "DUE DILIGENCE STATEMENT",
    subtitle: "Production country and parcel geolocation",
    emittedOn: "Issued on",
    filenamePrefix: "DDS",
    section1: "1. LOT INFORMATION",
    fieldLot: "LOT N°",
    fieldProduct: "PRODUCT",
    fieldWeight: "TOTAL WEIGHT",
    fieldOrigin: "COUNTRY OF ORIGIN",
    fieldDest: "DESTINATION",
    fieldBuyer: "BUYER",
    section2: "2. PARCELS & GEOLOCATION",
    colParcel: "PARCEL ID",
    colSurface: "SURFACE (HA)",
    colType: "TYPE",
    colLat: "LAT.",
    colLon: "LON.",
    colGeojson: "GEOJSON",
    typePoint: "Point",
    typePolygon: "Polygon",
    geojsonOui: "Yes",
    geojsonNon: "—",
    footerLeft: (name, code, date) =>
      `GENERATED BY ID BASSIN CONGO · EUDR SCRIPT V${EUDR_SCRIPT_VERSION}\nADMIN : ${name} (${code}) · ${date}`,
    footerRight: "AUTOMATICALLY GENERATED DOCUMENT — ID BASSIN CONGO",
    errNotAuthed: "Not authenticated",
    errInvalidToken: "Invalid token",
    errAdminOnly: "Administrators only",
    errLotNotFound: "Lot not found",
    errInternal: "Internal error",
  },
}

// ── PDF drawing helpers ────────────────────────────────────────────────────

function drawText(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  opts: { font: PDFFont; size: number; color?: ReturnType<typeof rgb> }
) {
  page.drawText(String(text ?? ""), {
    x, y,
    size: opts.size,
    font: opts.font,
    color: opts.color ?? DARK,
  })
}

function drawRect(
  page: PDFPage,
  x: number, y: number, w: number, h: number,
  fillColor: ReturnType<typeof rgb>,
  borderColor?: ReturnType<typeof rgb>
) {
  page.drawRectangle({
    x, y, width: w, height: h,
    color: fillColor,
    borderColor,
    borderWidth: borderColor ? 0.5 : 0,
  })
}

// Draw an info card (label + value) at given x,y with given width
function drawInfoCard(
  page: PDFPage,
  x: number, y: number, w: number, h: number,
  label: string, value: string,
  fonts: { regular: PDFFont; bold: PDFFont },
  valueColor: ReturnType<typeof rgb> = DARK
) {
  drawRect(page, x, y, w, h, LIGHT)
  drawText(page, label, x + 8, y + h - 14, { font: fonts.regular, size: 7, color: GRAY })
  drawText(page, value, x + 8, y + 8, { font: fonts.bold, size: 10, color: valueColor })
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ lotId: string }> }
) {
  const lang: Lang = request.nextUrl.searchParams.get("lang") === "en" ? "en" : "fr"
  const d = DICTS[lang]

  try {
    const { lotId } = await params

    // ── AUTH ──
    const token = request.cookies.get("auth-token")?.value
    if (!token) return NextResponse.json({ error: d.errNotAuthed }, { status: 401 })
    const payload = verifyToken(token)
    if (!payload) return NextResponse.json({ error: d.errInvalidToken }, { status: 401 })

    const { data: profile } = await supabaseAdmin
      .from("user_profiles")
      .select("role, nom_complet, user_code")
      .eq("id", payload.userId)
      .single()
    if (profile?.role !== "admin") return NextResponse.json({ error: d.errAdminOnly }, { status: 403 })

    const adminName = profile?.nom_complet ?? payload.email ?? "Admin"
    const adminCode = profile?.user_code ?? "USR-00001"

    // ── DATA ──
    const { data: lot, error: lotErr } = await supabaseAdmin
      .from("lots")
      .select("*, pays(nom)")
      .eq("id", lotId)
      .single()
    if (lotErr || !lot) return NextResponse.json({ error: d.errLotNotFound }, { status: 404 })

    const { data: lotCollectes } = await supabaseAdmin
      .from("lot_collectes")
      .select(`
        collectes (
          id,
          producteurs (id, code_producteur, nom, prenom),
          parcelles (
            id, code_parcelle, surface_ha, status_eudr,
            latitude, longitude, geojson,
            eudr_verification_timestamp, eudr_script_version
          )
        )
      `)
      .eq("lot_id", lotId)

    const collectes = (lotCollectes ?? []).map((lc: any) => lc.collectes).filter(Boolean) as any[]
    const parcellesMap = new Map<string, any>()
    collectes.forEach((c: any) => {
      if (c.parcelles) parcellesMap.set(String(c.parcelles.id), c.parcelles)
    })
    const parcelles = Array.from(parcellesMap.values())

    // ── BUILD PDF ──
    const pdf = await PDFDocument.create()
    const fontR = await pdf.embedFont(StandardFonts.Helvetica)
    const fontB = await pdf.embedFont(StandardFonts.HelveticaBold)

    const generationDate = new Date()
    const emittedDate = generationDate.toLocaleDateString(d.dateLocale, {
      day: "2-digit", month: "2-digit", year: "numeric",
    })
    const footerDate = `${generationDate.toLocaleDateString(d.dateLocale, { day: "2-digit", month: "2-digit", year: "numeric" })} ${generationDate.toLocaleTimeString(d.dateLocale, { hour: "2-digit", minute: "2-digit" })}`

    let page = pdf.addPage([PAGE_W, PAGE_H])
    let y = PAGE_H - 48

    function newPageIfNeeded(needed: number) {
      if (y - needed < MB) {
        drawPageFooter(page)
        page = pdf.addPage([PAGE_W, PAGE_H])
        y = PAGE_H - 48
      }
    }

    function drawPageFooter(pg: PDFPage) {
      // Footer separator line
      pg.drawLine({
        start: { x: ML, y: MB - 8 },
        end: { x: MR, y: MB - 8 },
        thickness: 0.5,
        color: LIGHT,
      })
      const footerLeft = d.footerLeft(adminName, adminCode, footerDate)
      const lines = footerLeft.split("\n")
      lines.forEach((line, i) => {
        pg.drawText(line, {
          x: ML, y: MB - 22 - i * 10,
          size: 6.5, font: fontR, color: GRAY,
        })
      })
      // Right-align footer right text
      const rightText = d.footerRight
      const rightW = fontR.widthOfTextAtSize(rightText, 6.5)
      pg.drawText(rightText, {
        x: MR - rightW, y: MB - 22,
        size: 6.5, font: fontR, color: GRAY,
      })
    }

    // ── PAGE 1: HEADER ──────────────────────────────────────────────────────

    // Left: org name (teal) + subtitle
    drawText(page, d.orgName, ML, y, { font: fontB, size: 14, color: TEAL })
    y -= 16
    drawText(page, d.subtitle, ML, y, { font: fontR, size: 9, color: GRAY })

    // Right: DDS label (teal) + reference + date
    const refText = lot.code_lot ? `DDS-${new Date().getFullYear()}-${lot.code_lot}` : `DDS-${new Date().getFullYear()}-${lotId}`
    // Check if a real DDS ref exists
    const { data: ddsRow } = await supabaseAdmin
      .from("dds")
      .select("reference_dds")
      .eq("lot_id", lotId)
      .single()
    const ddsRef = ddsRow?.reference_dds ?? refText

    const ddsLabelW = fontB.widthOfTextAtSize(d.ddsLabel, 8)
    const refW = fontB.widthOfTextAtSize(ddsRef, 13)
    const dateStr = `${d.emittedOn} ${emittedDate}`
    const dateW = fontR.widthOfTextAtSize(dateStr, 9)

    const headerY = PAGE_H - 48
    drawText(page, d.ddsLabel, MR - ddsLabelW, headerY, { font: fontB, size: 8, color: TEAL })
    drawText(page, ddsRef, MR - refW, headerY - 16, { font: fontB, size: 13, color: DARK })
    drawText(page, dateStr, MR - dateW, headerY - 32, { font: fontR, size: 9, color: GRAY })

    y = headerY - 50

    // Thick separator line
    page.drawLine({
      start: { x: ML, y },
      end: { x: MR, y },
      thickness: 2,
      color: DARK,
    })
    y -= 22

    // ── SECTION 1: LOT INFO ─────────────────────────────────────────────────

    drawText(page, d.section1, ML, y, { font: fontB, size: 8.5, color: DARK })
    y -= 18

    const CARD_H = 46
    const CARD_GAP = 6
    const CARD_W = (MR - ML - CARD_GAP * 2) / 3

    const row1 = [
      { label: d.fieldLot, value: lot.code_lot ?? "-", color: TEAL },
      { label: d.fieldProduct, value: lot.produit ?? "-", color: DARK },
      { label: d.fieldWeight, value: `${parseFloat(lot.poids_total_kg || "0").toFixed(2)} kg`, color: DARK },
    ]
    row1.forEach((card, i) => {
      const cx = ML + i * (CARD_W + CARD_GAP)
      drawInfoCard(page, cx, y - CARD_H, CARD_W, CARD_H, card.label, card.value, { regular: fontR, bold: fontB }, card.color)
    })
    y -= CARD_H + CARD_GAP

    const row2 = [
      { label: d.fieldOrigin, value: lot.pays?.nom ?? lot.pays_origine ?? "-", color: DARK },
      { label: d.fieldDest, value: lot.destination_pays ?? "-", color: DARK },
      { label: d.fieldBuyer, value: lot.acheteur ?? "-", color: DARK },
    ]
    row2.forEach((card, i) => {
      const cx = ML + i * (CARD_W + CARD_GAP)
      drawInfoCard(page, cx, y - CARD_H, CARD_W, CARD_H, card.label, card.value, { regular: fontR, bold: fontB }, card.color)
    })
    y -= CARD_H + 22

    // ── SECTION 2: PARCELLES TABLE ──────────────────────────────────────────

    newPageIfNeeded(30 + parcelles.length * 22 + 50)

    drawText(page, d.section2, ML, y, { font: fontB, size: 8.5, color: DARK })
    y -= 14

    // Table column widths
    const TABLE_W = MR - ML
    const COL_WIDTHS = [110, 80, 65, 65, 65, 55]  // parcel, surface, type, lat, lon, geojson
    const COL_HEADERS = [d.colParcel, d.colSurface, d.colType, d.colLat, d.colLon, d.colGeojson]
    const ROW_H = 20
    const HEADER_H = 22

    // Header row (dark background)
    drawRect(page, ML, y - HEADER_H, TABLE_W, HEADER_H, rgb(0.1, 0.1, 0.1))
    let cx2 = ML
    COL_HEADERS.forEach((h, i) => {
      drawText(page, h, cx2 + 6, y - HEADER_H + 7, { font: fontB, size: 6.5, color: WHITE })
      cx2 += COL_WIDTHS[i]
    })
    y -= HEADER_H

    // Data rows
    parcelles.forEach((p, idx) => {
      newPageIfNeeded(ROW_H + 4)
      const rowBg = idx % 2 === 0 ? WHITE : rgb(0.985, 0.985, 0.985)
      drawRect(page, ML, y - ROW_H, TABLE_W, ROW_H, rowBg)

      // Row separator
      page.drawLine({
        start: { x: ML, y: y - ROW_H },
        end: { x: MR, y: y - ROW_H },
        thickness: 0.3,
        color: rgb(0.9, 0.9, 0.9),
      })

      const hasGeo = p.geojson != null
      const hasPoint = p.latitude != null && p.longitude != null
      const type = hasGeo ? d.typePolygon : (hasPoint ? d.typePoint : "—")
      const geoText = (hasGeo || hasPoint) ? d.geojsonOui : d.geojsonNon

      const values = [
        { text: p.code_parcelle, color: TEAL },
        { text: p.surface_ha != null ? String(p.surface_ha) : "—", color: DARK },
        { text: type, color: DARK },
        { text: p.latitude != null ? Number(p.latitude).toFixed(4) : "—", color: DARK },
        { text: p.longitude != null ? Number(p.longitude).toFixed(4) : "—", color: DARK },
        { text: geoText, color: geoText === d.geojsonOui ? TEAL : GRAY },
      ]

      let vx = ML
      values.forEach((v, i) => {
        drawText(page, v.text, vx + 6, y - ROW_H + 6, {
          font: i === 0 ? fontB : fontR,
          size: 8,
          color: v.color,
        })
        vx += COL_WIDTHS[i]
      })
      y -= ROW_H
    })

    // Table bottom border
    page.drawLine({
      start: { x: ML, y },
      end: { x: MR, y },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85),
    })

    // ── DRAW FOOTER ON LAST PAGE ──
    drawPageFooter(page)

    // ── RETURN PDF ──
    const pdfBytes = await pdf.save()
    return new NextResponse(Buffer.from(pdfBytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${d.filenamePrefix}_${ddsRef}_${lang}_${generationDate.toISOString().split("T")[0]}.pdf"`,
        "Cache-Control": "no-store",
      },
    })
  } catch (err: any) {
    console.error("[generate-dss]", err)
    return NextResponse.json({ error: err.message ?? DICTS[lang].errInternal }, { status: 500 })
  }
}
