"use client"
import Link from "next/link"
import { useMemo, useState } from "react"
import { useLanguage } from "@/contexts/LanguageContext"
import ConfirmModal from "@/components/ConfirmModal"
import * as XLSX from "xlsx"

type Lot = {
  id: number
  code_lot: string
  produit: string | null
  poids_total_kg: string
  statut: string | null
  date_creation?: string | null
}

type DdsRow = {
  ddsId: number | null
  refDds: string
  lotCode: string
  lotId: number
  produit: string
  poidsKg: number
  dateGeneration: string
  statut: "en_preparation" | "pret" | "exporte"
  generePar: string
}

function exportExcel(
  rows: DdsRow[],
  locale: string,
  statutLabel: (s: DdsRow["statut"]) => string,
) {
  const isEn = locale === "en"
  const headers = isEn
    ? ["DDS Reference", "Linked Lot", "Product", "Weight (kg)", "Generation Date", "Status", "Generated By"]
    : ["Référence DDS", "Lot lié", "Produit", "Poids (kg)", "Date génération", "Statut", "Généré par"]
  const data = [
    headers,
    ...rows.map((r) => [
      r.refDds,
      r.lotCode,
      r.produit,
      r.poidsKg,
      r.dateGeneration,
      statutLabel(r.statut),
      r.generePar,
    ]),
  ]
  const ws = XLSX.utils.aoa_to_sheet(data)
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, isEn ? "DDS Export" : "Export DDS")
  XLSX.writeFile(wb, `dds-export-${new Date().toISOString().split("T")[0]}.xlsx`)
}

function makeDdsRef(lotId: number, index: number): string {
  const year = 2025
  const seq = String(index + 1).padStart(4, "0")
  return `DDS-${year}-${seq}`
}

function lotStatutToDds(statut: string | null): DdsRow["statut"] {
  if (!statut) return "en_preparation"
  const s = statut.toLowerCase()
  if (s === "exporté" || s === "exporte" || s === "exported") return "exporte"
  if (s === "prêt" || s === "pret" || s === "ready") return "pret"
  return "en_preparation"
}

type DdsDbRecord = {
  id: number
  reference_dds: string
  statut: string
  created_at: string
  genere_par_nom: string | null
}

export default function ExportContent({
  lots,
  collectesParLot,
  currentUserName,
  ddsByLot = {},
}: {
  lots: Lot[]
  collectesParLot: Record<number, number>
  currentUserName: string
  ddsByLot?: Record<number, DdsDbRecord>
}) {
  const { t, locale } = useLanguage()
  const e = t.export
  const [search, setSearch] = useState("")
  const [filterStatut, setFilterStatut] = useState<string>("all")
  const [page, setPage] = useState(1)
  const [deleteId, setDeleteId] = useState<number | null>(null)

  async function handleDelete() {
    if (!deleteId) return
    await fetch(`/api/dds/${deleteId}/delete`, { method: "POST" })
    setDeleteId(null)
    window.location.reload()
  }
  const PAGE_SIZE = 10

  function handleSearch(v: string) { setSearch(v); setPage(1) }
  function handleFilter(v: string) { setFilterStatut(v); setPage(1) }

  const ddsRows: DdsRow[] = useMemo(() => {
    const dateLocale = locale === "en" ? "en-GB" : "fr-FR"
    return lots
      .map((lot, i) => {
        const real = ddsByLot[lot.id]
        const dateGeneration = real
          ? new Date(real.created_at).toLocaleDateString(dateLocale, { day: "2-digit", month: "2-digit", year: "numeric" })
          : lot.date_creation
            ? new Date(lot.date_creation).toLocaleDateString(dateLocale, { day: "2-digit", month: "2-digit", year: "numeric" })
            : "-"
        const sortTs = real
          ? new Date(real.created_at).getTime()
          : lot.date_creation
            ? new Date(lot.date_creation).getTime()
            : 0
        return {
          ddsId: real ? real.id : null,
          refDds: real ? real.reference_dds : makeDdsRef(lot.id, i),
          lotCode: lot.code_lot,
          lotId: lot.id,
          produit: lot.produit ?? "-",
          poidsKg: parseFloat(lot.poids_total_kg) || 0,
          dateGeneration,
          statut: real ? lotStatutToDds(real.statut) : lotStatutToDds(lot.statut),
          generePar: real?.genere_par_nom ?? currentUserName,
          sortTs,
        }
      })
      .sort((a, b) => b.sortTs - a.sortTs)
      .map(({ sortTs: _, ...row }) => row)
  }, [lots, locale, currentUserName, ddsByLot])

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase()
    return ddsRows.filter((row) => {
      const matchSearch =
        !q ||
        row.refDds.toLowerCase().includes(q) ||
        row.lotCode.toLowerCase().includes(q) ||
        row.produit.toLowerCase().includes(q)
      const matchStatut = filterStatut === "all" || row.statut === filterStatut
      return matchSearch && matchStatut
    })
  }, [ddsRows, search, filterStatut])

  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE))
  const paginated = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE)

  const stats = useMemo(() => {
    const generated = ddsRows.length
    const submitted = ddsRows.filter((r) => r.statut === "exporte").length
    const pending = ddsRows.filter((r) => r.statut === "en_preparation").length
    const totalExportKg = ddsRows
      .filter((r) => r.statut === "exporte")
      .reduce((sum, r) => sum + r.poidsKg, 0)
    return { generated, submitted, pending, totalExportKg }
  }, [ddsRows])

  function statutLabel(s: DdsRow["statut"]): string {
    if (s === "pret") return e.statutPret
    if (s === "exporte") return e.statutExporte
    return e.statutEnPreparation
  }

  function statutColors(s: DdsRow["statut"]): string {
    if (s === "exporte") return "bg-[#d7efe5] text-[#2f7a5c] border border-[#2f7a5c33]"
    if (s === "pret") return "bg-[#e8e4f6] text-[#3b2a7a] border border-[#3b2a7a33]"
    return "bg-[#faecc2] text-[#6b3a12] border border-[#6b3a1233]"
  }

  const formatWeight = (kg: number): string => {
    if (kg >= 1000) {
      return (
        Math.round(kg)
          .toString()
          .replace(/\B(?=(\d{3})+(?!\d))/g, " ") + " kg"
      )
    }
    return kg.toFixed(2) + " kg"
  }

  const statCards = [
    { label: e.statGenerated, value: stats.generated, color: "text-gray-900" },
    { label: e.statSubmitted, value: stats.submitted, color: "text-[#2AC1A3]" },
    { label: e.statPending,   value: stats.pending,   color: "text-[#b8844a]" },
    { label: e.statTotalExport, value: formatWeight(stats.totalExportKg), color: "text-gray-900" },
  ]

  return (
    <div className="space-y-5 sm:space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="min-w-0">
          <p className="text-[10px] sm:text-[11px] tracking-[0.2em] sm:tracking-[0.25em] uppercase mb-2 sm:mb-3 font-mono">
            <span className="text-gray-400">ID BASSIN CONGO / </span>
            <span className="text-[#2AC1A3] font-semibold">{e.title}</span>
          </p>
          <h1 className="font-archivo text-[28px] font-bold text-gray-900 tracking-tight uppercase" style={{ fontFamily: "var(--font-archivo-narrow)" }}>
            {e.title}
          </h1>
        </div>
        <div className="flex items-center gap-2 self-start sm:self-auto shrink-0">
          <button
            onClick={() => exportExcel(ddsRows, locale, statutLabel)}
            className="px-4 sm:px-5 py-2.5 border border-gray-300 text-[10px] sm:text-[11px] font-bold tracking-[0.15em] sm:tracking-[0.18em] text-gray-600 hover:bg-gray-50 rounded-lg transition font-mono uppercase"
          >
            {e.btnExport}
          </button>
          <Link
            href="/export/generate"
            className="px-4 sm:px-6 py-2.5 bg-[#2AC1A3] hover:bg-[#25ad92] text-white text-[10px] sm:text-[11px] font-bold tracking-[0.15em] sm:tracking-[0.18em] rounded-lg transition font-mono shadow-sm whitespace-nowrap uppercase"
          >
            {e.btnGenerateDds}
          </Link>
        </div>
      </div>

      {/* Stats cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        {statCards.map((s) => (
          <div
            key={s.label}
            className="bg-white border border-gray-200 px-4 sm:px-6 py-3 sm:py-4"
            style={{ borderRadius: 10 }}
          >
            <p className="text-[9px] sm:text-[10px] text-gray-400 tracking-[0.15em] sm:tracking-[0.2em] uppercase font-mono mb-1.5 sm:mb-2 truncate">
              {s.label}
            </p>
            <p className={`text-[26px] sm:text-[32px] leading-none font-bold mb-1.5 sm:mb-2 ${s.color}`} style={{ fontFamily: "var(--font-archivo-narrow)" }}>
              {s.value}
            </p>
          </div>
        ))}
      </div>

      {/* Search + Filter */}
      <div className="bg-white border border-gray-200 rounded-xl p-4 flex flex-col sm:flex-row gap-3">
        <input
          type="text"
          placeholder={locale === "en" ? "Search DDS, lot, product…" : "Rechercher DDS, lot, produit…"}
          value={search}
          onChange={(ev) => handleSearch(ev.target.value)}
          className="flex-1 px-4 py-2.5 bg-white text-gray-900 border border-gray-200 rounded-lg text-sm placeholder-gray-400 focus:outline-none focus:border-[#2AC1A3] focus:ring-1 focus:ring-[#2AC1A3] font-mono"
        />
        <select
          value={filterStatut}
          onChange={(ev) => handleFilter(ev.target.value)}
          className="sm:w-52 px-4 py-2.5 bg-white text-gray-700 border border-gray-200 rounded-lg text-[11px] font-mono tracking-[0.12em] uppercase focus:outline-none focus:border-[#2AC1A3] focus:ring-1 focus:ring-[#2AC1A3] transition"
        >
          <option value="all">{locale === "en" ? "All statuses" : "Tous les statuts"}</option>
          <option value="en_preparation">{e.statutEnPreparation}</option>
          <option value="pret">{e.statutPret}</option>
          <option value="exporte">{e.statutExporte}</option>
        </select>
      </div>

      {/* Mobile card list */}
      {paginated.length > 0 && (
        <div className="sm:hidden space-y-3">
          {paginated.map((row) => (
            <div key={row.refDds} className="bg-white border border-gray-200 rounded-xl p-4 space-y-3">
              <div className="flex items-start justify-between gap-3">
                <Link
                  href={row.ddsId ? `/export/${row.ddsId}` : `/lots/${row.lotId}`}
                  className="text-[#2AC1A3] font-mono font-semibold text-[13px] hover:underline leading-tight"
                >
                  {row.refDds}
                </Link>
                <span className={`shrink-0 inline-block min-w-[130px] text-center px-2.5 py-1 rounded-full text-[8px] font-semibold tracking-[0.12em] uppercase font-mono whitespace-nowrap ${statutColors(row.statut)}`}>
                  {statutLabel(row.statut)}
                </span>
              </div>
              <div className="grid grid-cols-2 gap-2 text-[11px]">
                <div>
                  <p className="text-gray-400 uppercase tracking-widest text-[9px] font-mono mb-0.5">{e.colLotLie}</p>
                  <p className="text-gray-700 font-mono">{row.lotCode}</p>
                </div>
                <div>
                  <p className="text-gray-400 uppercase tracking-widest text-[9px] font-mono mb-0.5">{e.colProduit}</p>
                  <p className="text-gray-700">{row.produit}</p>
                </div>
                <div>
                  <p className="text-gray-400 uppercase tracking-widest text-[9px] font-mono mb-0.5">{e.colPoids}</p>
                  <p className="font-semibold text-gray-900">
                    {row.poidsKg.toLocaleString(locale === "en" ? "en-GB" : "fr-FR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} kg
                  </p>
                </div>
                <div>
                  <p className="text-gray-400 uppercase tracking-widest text-[9px] font-mono mb-0.5">{e.colDateGen}</p>
                  <p className="text-gray-500 font-mono">{row.dateGeneration}</p>
                </div>
              </div>
              <div className="flex items-center gap-4 pt-1 border-t border-gray-100 text-[10px] tracking-[0.12em] font-semibold uppercase font-mono">
                <Link
                  href={row.ddsId ? `/export/${row.ddsId}` : `/lots/${row.lotId}`}
                  className="text-gray-400 hover:text-gray-600 transition"
                >
                  {e.actionView}
                </Link>
                <Link
                  href={row.ddsId ? `/export/${row.ddsId}/edit` : `/lots/${row.lotId}/edit`}
                  className="text-[#2AC1A3] hover:text-[#1da88e] transition"
                >
                  {e.actionEdit}
                </Link>
                <a
                  href={`/api/generate-dss/${row.lotId}?lang=${locale}`}
                  download
                  className="text-[#3b82f6] hover:text-[#2563eb] transition"
                >
                  {e.actionDownload}
                </a>
                {row.ddsId && (
                  <button onClick={() => setDeleteId(row.ddsId)} className="text-red-400 hover:text-red-600 transition">
                    {t.referentiel.delete}
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Desktop table */}
      <div className="hidden sm:block bg-white rounded-xl border border-gray-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full" style={{ fontFamily: "var(--font-courier-prime)" }}>
            <thead>
              <tr className="bg-[#F7F8FA] border-b border-gray-200">
                {[e.colRefDds, e.colLotLie, e.colProduit, e.colPoids, e.colDateGen, e.colStatut, e.colGenPar, e.colActions].map((col) => (
                  <th
                    key={col}
                    className="px-4 lg:px-6 py-3.5 text-left text-[10px] font-semibold text-gray-400 tracking-[0.2em] uppercase font-mono whitespace-nowrap"
                  >
                    {col}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {paginated.map((row) => (
                <tr key={row.refDds} className="border-b border-gray-100 last:border-0 hover:bg-gray-50/60 transition">
                  <td className="px-4 lg:px-6 py-4">
                    <Link
                      href={row.ddsId ? `/export/${row.ddsId}` : `/lots/${row.lotId}`}
                      className="text-[#2AC1A3] hover:underline font-mono font-semibold text-[13px] lg:text-[14px]"
                    >
                      {row.refDds}
                    </Link>
                  </td>
                  <td className="px-4 lg:px-6 py-4 text-[13px] lg:text-[14px] text-gray-700 font-mono">
                    {row.lotCode}
                  </td>
                  <td className="px-4 lg:px-6 py-4 text-[13px] lg:text-[14px] text-gray-700" style={{ fontFamily: "var(--font-archivo-narrow)" }}>
                    {row.produit}
                  </td>
                  <td className="px-4 lg:px-6 py-4 text-[13px] lg:text-[14px] font-semibold text-gray-900" style={{ fontFamily: "var(--font-archivo-narrow)" }}>
                    {row.poidsKg.toLocaleString(locale === "en" ? "en-GB" : "fr-FR", {
                      minimumFractionDigits: 2,
                      maximumFractionDigits: 2,
                    })}
                  </td>
                  <td className="px-4 lg:px-6 py-4 text-[12px] lg:text-[13px] text-gray-500 font-mono">
                    {row.dateGeneration}
                  </td>
                  <td className="px-4 lg:px-6 py-4">
                    <span
                      className={`inline-block min-w-[130px] text-center px-2.5 lg:px-3 py-1 rounded-full text-[8px] lg:text-[9px] font-semibold tracking-[0.12em] lg:tracking-[0.15em] uppercase font-mono whitespace-nowrap ${statutColors(row.statut)}`}
                    >
                      {statutLabel(row.statut)}
                    </span>
                  </td>
                  <td className="px-4 lg:px-6 py-4 text-[12px] lg:text-[13px] text-gray-600" style={{ fontFamily: "var(--font-archivo-narrow)" }}>
                    {row.generePar}
                  </td>
                  <td className="px-4 lg:px-6 py-4">
                    <div className="flex items-center gap-3 lg:gap-5 text-[9px] lg:text-[10px] tracking-[0.12em] lg:tracking-[0.15em] font-semibold uppercase font-mono whitespace-nowrap">
                      <Link
                        href={row.ddsId ? `/export/${row.ddsId}` : `/lots/${row.lotId}`}
                        className="text-gray-400 hover:text-gray-600 transition"
                      >
                        {e.actionView}
                      </Link>
                      <Link
                        href={row.ddsId ? `/export/${row.ddsId}/edit` : `/lots/${row.lotId}/edit`}
                        className="text-[#2AC1A3] hover:text-[#1da88e] transition"
                      >
                        {e.actionEdit}
                      </Link>
                      <a
                        href={`/api/generate-dss/${row.lotId}?lang=${locale}`}
                        download
                        className="text-[#3b82f6] hover:text-[#2563eb] transition"
                      >
                        {e.actionDownload}
                      </a>
                      {row.ddsId && (
                        <button onClick={() => setDeleteId(row.ddsId)} className="text-red-400 hover:text-red-600 transition">
                          {t.referentiel.delete}
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {filtered.length === 0 && (
          <div className="p-8 lg:p-12 text-center">
            <p className="text-gray-400 text-[13px] font-mono mb-3">{e.empty}</p>
            <Link
              href="/lots/nouveau"
              className="text-[#2AC1A3] hover:underline text-[13px] font-semibold font-mono"
            >
              {e.createLot}
            </Link>
          </div>
        )}
      </div>

      {filtered.length === 0 && (
        <div className="sm:hidden bg-white rounded-xl border border-gray-200 p-8 text-center">
          <p className="text-gray-400 text-[13px] font-mono mb-3">{e.empty}</p>
          <Link href="/lots/nouveau" className="text-[#2AC1A3] hover:underline text-[13px] font-semibold font-mono">
            {e.createLot}
          </Link>
        </div>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex flex-col items-center sm:flex-row sm:items-center sm:justify-between gap-3">
          <p className="text-[10px] text-gray-400 font-mono tracking-[0.12em] uppercase text-center sm:text-left">
            {locale === "en"
              ? `${filtered.length} result${filtered.length !== 1 ? "s" : ""} · page ${page} of ${totalPages}`
              : `${filtered.length} résultat${filtered.length !== 1 ? "s" : ""} · page ${page} sur ${totalPages}`}
          </p>
          <div className="flex items-center justify-center gap-1 flex-wrap">
            <button
              onClick={() => setPage(1)}
              disabled={page === 1}
              className="px-2.5 py-1.5 text-[10px] font-mono tracking-widest text-gray-500 border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed transition"
            >
              «
            </button>
            <button
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page === 1}
              className="px-3 py-1.5 text-[10px] font-mono tracking-widest text-gray-500 border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed transition"
            >
              ‹
            </button>
            {Array.from({ length: totalPages }, (_, i) => i + 1)
              .filter((p) => p === 1 || p === totalPages || Math.abs(p - page) <= 1)
              .reduce<(number | "…")[]>((acc, p, idx, arr) => {
                if (idx > 0 && p - (arr[idx - 1] as number) > 1) acc.push("…")
                acc.push(p)
                return acc
              }, [])
              .map((p, idx) =>
                p === "…" ? (
                  <span key={`ellipsis-${idx}`} className="px-2 text-gray-300 text-[10px] font-mono">…</span>
                ) : (
                  <button
                    key={p}
                    onClick={() => setPage(p as number)}
                    className={`px-3 py-1.5 text-[10px] font-mono tracking-widest rounded-lg border transition ${
                      page === p
                        ? "bg-[#2AC1A3] text-white border-[#2AC1A3] font-bold"
                        : "text-gray-500 border-gray-200 hover:bg-gray-50"
                    }`}
                  >
                    {p}
                  </button>
                )
              )}
            <button
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page === totalPages}
              className="px-3 py-1.5 text-[10px] font-mono tracking-widest text-gray-500 border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed transition"
            >
              ›
            </button>
            <button
              onClick={() => setPage(totalPages)}
              disabled={page === totalPages}
              className="px-2.5 py-1.5 text-[10px] font-mono tracking-widest text-gray-500 border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed transition"
            >
              »
            </button>
          </div>
        </div>
      )}

      <ConfirmModal
        open={deleteId !== null}
        title={t.referentiel.deleteTitle}
        message={locale === "fr" ? "Supprimer ce DDS ? Cette action est irréversible." : "Delete this DDS? This action cannot be undone."}
        confirmLabel={t.referentiel.delete}
        cancelLabel={t.referentiel.cancel}
        onConfirm={handleDelete}
        onCancel={() => setDeleteId(null)}
      />
    </div>
  )
}
